name: gymhub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  data_table_2: ^2.6.0
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# 🔽 Esta es la sección donde se configura todo lo relacionado a Flutter:
flutter:
  uses-material-design: true

  # 🔽 Aquí se cargan los assets (como imágenes, íconos, etc.)
  assets:
    - assets/images/logo/
